variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install    

- task: Npm@1
  displayName: 'build app'
  inputs:
    command: custom
    customCommand: run build -- --prod

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'dist'
